language: node_js

node_js: 'stable'

services:
  - postgresql

env:
  - PORT=4000

notifications:
  email: false

before_script:
  - createdb phantom-test-db -U postgres
  - npm ci
  - npm run migrate:test

script: npm run coverage

after_success: npm run coveralls
